CREATE TYPE "public"."type" AS ENUM('channel', 'group');--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "giveaway_location" (
	"type" "type",
	"id" integer PRIMARY KEY NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "giveaway" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "giveaway_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"locationId" integer
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "user" (
	"id" integer PRIMARY KEY NOT NULL,
	"username" varchar(255),
	"firstName" varchar(255),
	CONSTRAINT "user_username_unique" UNIQUE("username")
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "giveaway" ADD CONSTRAINT "giveaway_locationId_giveaway_location_id_fk" FOREIGN KEY ("locationId") REFERENCES "public"."giveaway_location"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
